//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class ColumnDescriptor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ColumnDescriptor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ColumnDescriptor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ColumnDescriptor() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_ColumnDescriptor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ColumnDescriptor() : this(RakNetPINVOKE.CSharp_RakNet_new_ColumnDescriptor__SWIG_0(), true) {
  }

  public ColumnDescriptor(string cn, Table.ColumnType ct) : this(RakNetPINVOKE.CSharp_RakNet_new_ColumnDescriptor__SWIG_1(cn, (int)ct), true) {
  }

  public string columnName {
    set {
      RakNetPINVOKE.CSharp_RakNet_ColumnDescriptor_columnName_set(swigCPtr, value);
    } 
    get {
      string ret = RakNetPINVOKE.CSharp_RakNet_ColumnDescriptor_columnName_get(swigCPtr);
      return ret;
    } 
  }

  public Table.ColumnType columnType {
    set {
      RakNetPINVOKE.CSharp_RakNet_ColumnDescriptor_columnType_set(swigCPtr, (int)value);
    } 
    get {
      Table.ColumnType ret = (Table.ColumnType)RakNetPINVOKE.CSharp_RakNet_ColumnDescriptor_columnType_get(swigCPtr);
      return ret;
    } 
  }

}

}
