//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
namespace RakNet {

public class FileListNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FileListNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FileListNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FileListNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_FileListNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    private bool dataIsCached = false;
    private byte[] dataCache;

  public RakString filename {
    set {
      RakNetPINVOKE.CSharp_RakNet_FileListNode_filename_set(swigCPtr, RakString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_FileListNode_filename_get(swigCPtr);
      RakString ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakString(cPtr, false);
      return ret;
    } 
  }

  public RakString fullPathToFile {
    set {
      RakNetPINVOKE.CSharp_RakNet_FileListNode_fullPathToFile_set(swigCPtr, RakString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_FileListNode_fullPathToFile_get(swigCPtr);
      RakString ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakString(cPtr, false);
      return ret;
    } 
  }

  public byte[] data {
	set 
	{
	    	dataCache=value;
		dataIsCached = true;
		SetData (value, value.Length);    
	}

        get
        {
            byte[] returnArray;
            if (!dataIsCached)
            {
                IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_FileListNode_data_get (swigCPtr);
                int len = (int) dataLengthBytes;
		if (len<=0)
		{
			return null;
		}
                returnArray = new byte[len];
                byte[] marshalArray = new byte[len];
                Marshal.Copy(cPtr, marshalArray, 0, len);
                marshalArray.CopyTo(returnArray, 0);
                dataCache = returnArray;
                dataIsCached = true;
            }
            else
            {
                returnArray = dataCache;
            }
            return returnArray;
        }
 
  }

  public uint dataLengthBytes {
    set {
      RakNetPINVOKE.CSharp_RakNet_FileListNode_dataLengthBytes_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.CSharp_RakNet_FileListNode_dataLengthBytes_get(swigCPtr);
      return ret;
    } 
  }

  public uint fileLengthBytes {
    set {
      RakNetPINVOKE.CSharp_RakNet_FileListNode_fileLengthBytes_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.CSharp_RakNet_FileListNode_fileLengthBytes_get(swigCPtr);
      return ret;
    } 
  }

  public FileListNodeContext context {
    set {
      RakNetPINVOKE.CSharp_RakNet_FileListNode_context_set(swigCPtr, FileListNodeContext.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_FileListNode_context_get(swigCPtr);
      FileListNodeContext ret = (cPtr == global::System.IntPtr.Zero) ? null : new FileListNodeContext(cPtr, false);
      return ret;
    } 
  }

  public bool isAReference {
    set {
      RakNetPINVOKE.CSharp_RakNet_FileListNode_isAReference_set(swigCPtr, value);
    } 
    get {
      bool ret = RakNetPINVOKE.CSharp_RakNet_FileListNode_isAReference_get(swigCPtr);
      return ret;
    } 
  }

  public FileListNode() : this(RakNetPINVOKE.CSharp_RakNet_new_FileListNode(), true) {
  }

  public void SetData(byte[] inByteArray, int numBytes) {
    RakNetPINVOKE.CSharp_RakNet_FileListNode_SetData(swigCPtr, inByteArray, numBytes);
  }

}

}
