//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class NatPunchthroughDebugInterface_Printf : NatPunchthroughDebugInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal NatPunchthroughDebugInterface_Printf(global::System.IntPtr cPtr, bool cMemoryOwn) : base(RakNetPINVOKE.CSharp_RakNet_NatPunchthroughDebugInterface_Printf_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NatPunchthroughDebugInterface_Printf obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NatPunchthroughDebugInterface_Printf() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_NatPunchthroughDebugInterface_Printf(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override void OnClientMessage(string msg) {
    RakNetPINVOKE.CSharp_RakNet_NatPunchthroughDebugInterface_Printf_OnClientMessage(swigCPtr, msg);
  }

  public NatPunchthroughDebugInterface_Printf() : this(RakNetPINVOKE.CSharp_RakNet_new_NatPunchthroughDebugInterface_Printf(), true) {
  }

}

}
