//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class RakNetListFileListNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetListFileListNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RakNetListFileListNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetListFileListNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_RakNetListFileListNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public FileListNode this[int index]  
    {  
        get   
        {
            return Get((uint)index); // use indexto retrieve and return another value.    
        }  
        set   
        {
            Replace(value, value, (uint)index, "Not used", 0);// use index and value to set the value somewhere.   
        }  
    } 

  public RakNetListFileListNode() : this(RakNetPINVOKE.CSharp_RakNet_new_RakNetListFileListNode__SWIG_0(), true) {
  }

  public RakNetListFileListNode(RakNetListFileListNode original_copy) : this(RakNetPINVOKE.CSharp_RakNet_new_RakNetListFileListNode__SWIG_1(RakNetListFileListNode.getCPtr(original_copy)), true) {
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public RakNetListFileListNode CopyData(RakNetListFileListNode original_copy) {
    RakNetListFileListNode ret = new RakNetListFileListNode(RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_CopyData(swigCPtr, RakNetListFileListNode.getCPtr(original_copy)), false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FileListNode Get(uint position) {
    FileListNode ret = new FileListNode(RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Get(swigCPtr, position), false);
    return ret;
  }

  public void Push(FileListNode input, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Push(swigCPtr, FileListNode.getCPtr(input), file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public FileListNode Pop() {
    FileListNode ret = new FileListNode(RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Pop(swigCPtr), false);
    return ret;
  }

  public void Insert(FileListNode input, uint position, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Insert__SWIG_0(swigCPtr, FileListNode.getCPtr(input), position, file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Insert(FileListNode input, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Insert__SWIG_1(swigCPtr, FileListNode.getCPtr(input), file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Replace(FileListNode input, FileListNode filler, uint position, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Replace__SWIG_0(swigCPtr, FileListNode.getCPtr(input), FileListNode.getCPtr(filler), position, file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Replace(FileListNode input) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Replace__SWIG_1(swigCPtr, FileListNode.getCPtr(input));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAtIndex(uint position) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_RemoveAtIndex(swigCPtr, position);
  }

  public void RemoveAtIndexFast(uint position) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_RemoveAtIndexFast(swigCPtr, position);
  }

  public void RemoveFromEnd(uint num) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_RemoveFromEnd__SWIG_0(swigCPtr, num);
  }

  public void RemoveFromEnd() {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_RemoveFromEnd__SWIG_1(swigCPtr);
  }

  public uint Size() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Size(swigCPtr);
    return ret;
  }

  public void Clear(bool doNotDeallocateSmallBlocks, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Clear(swigCPtr, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(uint countNeeded, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Preallocate(swigCPtr, countNeeded, file, line);
  }

  public void Compress(string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListFileListNode_Compress(swigCPtr, file, line);
  }

}

}
