//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class RakNetListSortQuery : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetListSortQuery(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RakNetListSortQuery obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetListSortQuery() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_RakNetListSortQuery(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public SortQuery this[int index]  
    {  
        get   
        {
            return Get((uint)index); // use indexto retrieve and return another value.    
        }  
        set   
        {
            Replace(value, value, (uint)index, "Not used", 0);// use index and value to set the value somewhere.   
        }  
    } 

  public RakNetListSortQuery() : this(RakNetPINVOKE.CSharp_RakNet_new_RakNetListSortQuery__SWIG_0(), true) {
  }

  public RakNetListSortQuery(RakNetListSortQuery original_copy) : this(RakNetPINVOKE.CSharp_RakNet_new_RakNetListSortQuery__SWIG_1(RakNetListSortQuery.getCPtr(original_copy)), true) {
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public RakNetListSortQuery CopyData(RakNetListSortQuery original_copy) {
    RakNetListSortQuery ret = new RakNetListSortQuery(RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_CopyData(swigCPtr, RakNetListSortQuery.getCPtr(original_copy)), false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SortQuery Get(uint position) {
    SortQuery ret = new SortQuery(RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Get(swigCPtr, position), false);
    return ret;
  }

  public void Push(SortQuery input, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Push(swigCPtr, SortQuery.getCPtr(input), file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public SortQuery Pop() {
    SortQuery ret = new SortQuery(RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Pop(swigCPtr), false);
    return ret;
  }

  public void Insert(SortQuery input, uint position, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Insert__SWIG_0(swigCPtr, SortQuery.getCPtr(input), position, file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Insert(SortQuery input, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Insert__SWIG_1(swigCPtr, SortQuery.getCPtr(input), file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Replace(SortQuery input, SortQuery filler, uint position, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Replace__SWIG_0(swigCPtr, SortQuery.getCPtr(input), SortQuery.getCPtr(filler), position, file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Replace(SortQuery input) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Replace__SWIG_1(swigCPtr, SortQuery.getCPtr(input));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAtIndex(uint position) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_RemoveAtIndex(swigCPtr, position);
  }

  public void RemoveAtIndexFast(uint position) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_RemoveAtIndexFast(swigCPtr, position);
  }

  public void RemoveFromEnd(uint num) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_RemoveFromEnd__SWIG_0(swigCPtr, num);
  }

  public void RemoveFromEnd() {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_RemoveFromEnd__SWIG_1(swigCPtr);
  }

  public uint Size() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Size(swigCPtr);
    return ret;
  }

  public void Clear(bool doNotDeallocateSmallBlocks, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Clear(swigCPtr, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(uint countNeeded, string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Preallocate(swigCPtr, countNeeded, file, line);
  }

  public void Compress(string file, uint line) {
    RakNetPINVOKE.CSharp_RakNet_RakNetListSortQuery_Compress(swigCPtr, file, line);
  }

}

}
