//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class SortQuery : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SortQuery(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SortQuery obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SortQuery() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_SortQuery(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint columnIndex {
    set {
      RakNetPINVOKE.CSharp_RakNet_SortQuery_columnIndex_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.CSharp_RakNet_SortQuery_columnIndex_get(swigCPtr);
      return ret;
    } 
  }

  public Table.SortQueryType operation {
    set {
      RakNetPINVOKE.CSharp_RakNet_SortQuery_operation_set(swigCPtr, (int)value);
    } 
    get {
      Table.SortQueryType ret = (Table.SortQueryType)RakNetPINVOKE.CSharp_RakNet_SortQuery_operation_get(swigCPtr);
      return ret;
    } 
  }

  public SortQuery() : this(RakNetPINVOKE.CSharp_RakNet_new_SortQuery(), true) {
  }

}

}
