//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class UnsignedIntPointer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UnsignedIntPointer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UnsignedIntPointer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnsignedIntPointer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_UnsignedIntPointer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public UnsignedIntPointer() : this(RakNetPINVOKE.CSharp_RakNet_new_UnsignedIntPointer(), true) {
  }

  public void assign(uint value) {
    RakNetPINVOKE.CSharp_RakNet_UnsignedIntPointer_assign(swigCPtr, value);
  }

  public uint value() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_UnsignedIntPointer_value(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_unsigned_int cast() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_UnsignedIntPointer_cast(swigCPtr);
    SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
    return ret;
  }

  public static UnsignedIntPointer frompointer(SWIGTYPE_p_unsigned_int t) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_UnsignedIntPointer_frompointer(SWIGTYPE_p_unsigned_int.getCPtr(t));
    UnsignedIntPointer ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnsignedIntPointer(cPtr, false);
    return ret;
  }

}

}
