//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class UnsignedShortPointer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UnsignedShortPointer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(UnsignedShortPointer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnsignedShortPointer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_UnsignedShortPointer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public UnsignedShortPointer() : this(RakNetPINVOKE.CSharp_RakNet_new_UnsignedShortPointer(), true) {
  }

  public void assign(ushort value) {
    RakNetPINVOKE.CSharp_RakNet_UnsignedShortPointer_assign(swigCPtr, value);
  }

  public ushort value() {
    ushort ret = RakNetPINVOKE.CSharp_RakNet_UnsignedShortPointer_value(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_unsigned_short cast() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_UnsignedShortPointer_cast(swigCPtr);
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

  public static UnsignedShortPointer frompointer(SWIGTYPE_p_unsigned_short t) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_UnsignedShortPointer_frompointer(SWIGTYPE_p_unsigned_short.getCPtr(t));
    UnsignedShortPointer ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnsignedShortPointer(cPtr, false);
    return ret;
  }

}

}
