//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class FilterQuery : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FilterQuery(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FilterQuery obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FilterQuery() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_FilterQuery(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FilterQuery() : this(RakNetPINVOKE.CSharp_RakNet_new_FilterQuery__SWIG_0(), true) {
  }

  public FilterQuery(uint column, Cell cell, Table.FilterQueryType op) : this(RakNetPINVOKE.CSharp_RakNet_new_FilterQuery__SWIG_1(column, Cell.getCPtr(cell), (int)op), true) {
  }

  public string columnName {
    set {
      RakNetPINVOKE.CSharp_RakNet_FilterQuery_columnName_set(swigCPtr, value);
    } 
    get {
      string ret = RakNetPINVOKE.CSharp_RakNet_FilterQuery_columnName_get(swigCPtr);
      return ret;
    } 
  }

  public uint columnIndex {
    set {
      RakNetPINVOKE.CSharp_RakNet_FilterQuery_columnIndex_set(swigCPtr, value);
    } 
    get {
      uint ret = RakNetPINVOKE.CSharp_RakNet_FilterQuery_columnIndex_get(swigCPtr);
      return ret;
    } 
  }

  public Cell cellValue {
    set {
      RakNetPINVOKE.CSharp_RakNet_FilterQuery_cellValue_set(swigCPtr, Cell.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_FilterQuery_cellValue_get(swigCPtr);
      Cell ret = (cPtr == global::System.IntPtr.Zero) ? null : new Cell(cPtr, false);
      return ret;
    } 
  }

  public Table.FilterQueryType operation {
    set {
      RakNetPINVOKE.CSharp_RakNet_FilterQuery_operation_set(swigCPtr, (int)value);
    } 
    get {
      Table.FilterQueryType ret = (Table.FilterQueryType)RakNetPINVOKE.CSharp_RakNet_FilterQuery_operation_get(swigCPtr);
      return ret;
    } 
  }

}

}
