//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;

public class NetworkIDManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NetworkIDManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NetworkIDManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NetworkIDManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_NetworkIDManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public Dictionary<IntPtr, NetworkIDObject> pointerDictionary = new Dictionary<IntPtr, NetworkIDObject>();

     public NetworkIDObject GET_BASE_OBJECT_FROM_ID(ulong x)
     {
	return pointerDictionary[GET_BASE_OBJECT_FROM_IDORIG(x).GetIntPtr()];
     }


  public static NetworkIDManager GetInstance() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_NetworkIDManager_GetInstance();
    NetworkIDManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetworkIDManager(cPtr, false);
    return ret;
  }

  public static void DestroyInstance(NetworkIDManager i) {
    RakNetPINVOKE.CSharp_RakNet_NetworkIDManager_DestroyInstance(NetworkIDManager.getCPtr(i));
  }

  public NetworkIDManager() : this(RakNetPINVOKE.CSharp_RakNet_new_NetworkIDManager(), true) {
  }

  public void Clear() {
    RakNetPINVOKE.CSharp_RakNet_NetworkIDManager_Clear(swigCPtr);
  }

  protected NetworkIDObject GET_BASE_OBJECT_FROM_IDORIG(ulong x) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_NetworkIDManager_GET_BASE_OBJECT_FROM_IDORIG(swigCPtr, x);
    NetworkIDObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetworkIDObject(cPtr, false);
    return ret;
  }

}

}
