//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class RakNetPageRow : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetPageRow(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RakNetPageRow obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetPageRow() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_RakNetPageRow(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool isLeaf {
    set {
      RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_isLeaf_set(swigCPtr, value);
    } 
    get {
      bool ret = RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_isLeaf_get(swigCPtr);
      return ret;
    } 
  }

  public int size {
    set {
      RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_size_set(swigCPtr, value);
    } 
    get {
      int ret = RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_size_get(swigCPtr);
      return ret;
    } 
  }

  public RakNetPageRow next {
    set {
      RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_next_set(swigCPtr, RakNetPageRow.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_next_get(swigCPtr);
      RakNetPageRow ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakNetPageRow(cPtr, false);
      return ret;
    } 
  }

  public RakNetPageRow previous {
    set {
      RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_previous_set(swigCPtr, RakNetPageRow.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakNetPageRow_previous_get(swigCPtr);
      RakNetPageRow ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakNetPageRow(cPtr, false);
      return ret;
    } 
  }

  public RakNetPageRow() : this(RakNetPINVOKE.CSharp_RakNet_new_RakNetPageRow(), true) {
  }

}

}
