//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class RakPeer : RakPeerInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal RakPeer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(RakNetPINVOKE.CSharp_RakNet_RakPeer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RakPeer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakPeer() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_RakPeer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

	public override void GetIncomingPassword(ref string passwordData, ref int passwordDataLength  )
	{
		passwordData=CSharpGetIncomingPasswordHelper(passwordData,ref passwordDataLength);
	}

	public override void GetOfflinePingResponse( byte[] inOutByteArray, out uint length )
	{
		CSharpGetOfflinePingResponseHelper(inOutByteArray,out length);
	}

	public override bool GetConnectionList(out SystemAddress[] remoteSystems, ref ushort numberOfSystems)
	{
		RakNetListSystemAddress passVal= new RakNetListSystemAddress();
		bool returnVal = GetConnectionList(passVal,ref numberOfSystems);
		SystemAddress[] outVal = new SystemAddress[numberOfSystems];
		for (int i=0; i<numberOfSystems;i++)
		{
			outVal[i]=passVal[i];
		} 
		remoteSystems=outVal;
		return returnVal;
	}


  public RakPeer() : this(RakNetPINVOKE.CSharp_RakNet_new_RakPeer(), true) {
  }

  public override StartupResult Startup(uint maxConnections, SocketDescriptor socketDescriptors, uint socketDescriptorCount, int threadPriority) {
    StartupResult ret = (StartupResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Startup__SWIG_0(swigCPtr, maxConnections, SocketDescriptor.getCPtr(socketDescriptors), socketDescriptorCount, threadPriority);
    return ret;
  }

  public override StartupResult Startup(uint maxConnections, SocketDescriptor socketDescriptors, uint socketDescriptorCount) {
    StartupResult ret = (StartupResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Startup__SWIG_1(swigCPtr, maxConnections, SocketDescriptor.getCPtr(socketDescriptors), socketDescriptorCount);
    return ret;
  }

  public override bool InitializeSecurity(string publicKey, string privateKey, bool bRequireClientKey) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_InitializeSecurity__SWIG_0(swigCPtr, publicKey, privateKey, bRequireClientKey);
    return ret;
  }

  public override bool InitializeSecurity(string publicKey, string privateKey) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_InitializeSecurity__SWIG_1(swigCPtr, publicKey, privateKey);
    return ret;
  }

  public override void DisableSecurity() {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_DisableSecurity(swigCPtr);
  }

  public override void AddToSecurityExceptionList(string ip) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_AddToSecurityExceptionList(swigCPtr, ip);
  }

  public override void RemoveFromSecurityExceptionList(string ip) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoveFromSecurityExceptionList(swigCPtr, ip);
  }

  public override bool IsInSecurityExceptionList(string ip) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_IsInSecurityExceptionList(swigCPtr, ip);
    return ret;
  }

  public override void SetMaximumIncomingConnections(ushort numberAllowed) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetMaximumIncomingConnections(swigCPtr, numberAllowed);
  }

  public override uint GetMaximumIncomingConnections() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetMaximumIncomingConnections(swigCPtr);
    return ret;
  }

  public override ushort NumberOfConnections() {
    ushort ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_NumberOfConnections(swigCPtr);
    return ret;
  }

  public override void SetIncomingPassword(string passwordData, int passwordDataLength) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetIncomingPassword__SWIG_0(swigCPtr, passwordData, passwordDataLength);
  }

  public override ConnectionAttemptResult Connect(string host, ushort remotePort, string passwordData, int passwordDataLength, PublicKey publicKey, uint connectionSocketIndex, uint sendConnectionAttemptCount, uint timeBetweenSendConnectionAttemptsMS, uint timeoutTime) {
    ConnectionAttemptResult ret = (ConnectionAttemptResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Connect__SWIG_0(swigCPtr, host, remotePort, passwordData, passwordDataLength, PublicKey.getCPtr(publicKey), connectionSocketIndex, sendConnectionAttemptCount, timeBetweenSendConnectionAttemptsMS, timeoutTime);
    return ret;
  }

  public override ConnectionAttemptResult Connect(string host, ushort remotePort, string passwordData, int passwordDataLength, PublicKey publicKey, uint connectionSocketIndex, uint sendConnectionAttemptCount, uint timeBetweenSendConnectionAttemptsMS) {
    ConnectionAttemptResult ret = (ConnectionAttemptResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Connect__SWIG_1(swigCPtr, host, remotePort, passwordData, passwordDataLength, PublicKey.getCPtr(publicKey), connectionSocketIndex, sendConnectionAttemptCount, timeBetweenSendConnectionAttemptsMS);
    return ret;
  }

  public override ConnectionAttemptResult Connect(string host, ushort remotePort, string passwordData, int passwordDataLength, PublicKey publicKey, uint connectionSocketIndex, uint sendConnectionAttemptCount) {
    ConnectionAttemptResult ret = (ConnectionAttemptResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Connect__SWIG_2(swigCPtr, host, remotePort, passwordData, passwordDataLength, PublicKey.getCPtr(publicKey), connectionSocketIndex, sendConnectionAttemptCount);
    return ret;
  }

  public override ConnectionAttemptResult Connect(string host, ushort remotePort, string passwordData, int passwordDataLength, PublicKey publicKey, uint connectionSocketIndex) {
    ConnectionAttemptResult ret = (ConnectionAttemptResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Connect__SWIG_3(swigCPtr, host, remotePort, passwordData, passwordDataLength, PublicKey.getCPtr(publicKey), connectionSocketIndex);
    return ret;
  }

  public override ConnectionAttemptResult Connect(string host, ushort remotePort, string passwordData, int passwordDataLength, PublicKey publicKey) {
    ConnectionAttemptResult ret = (ConnectionAttemptResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Connect__SWIG_4(swigCPtr, host, remotePort, passwordData, passwordDataLength, PublicKey.getCPtr(publicKey));
    return ret;
  }

  public override ConnectionAttemptResult Connect(string host, ushort remotePort, string passwordData, int passwordDataLength) {
    ConnectionAttemptResult ret = (ConnectionAttemptResult)RakNetPINVOKE.CSharp_RakNet_RakPeer_Connect__SWIG_5(swigCPtr, host, remotePort, passwordData, passwordDataLength);
    return ret;
  }

  public override void Shutdown(uint blockDuration, byte orderingChannel, PacketPriority disconnectionNotificationPriority) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_Shutdown__SWIG_0(swigCPtr, blockDuration, orderingChannel, (int)disconnectionNotificationPriority);
  }

  public override void Shutdown(uint blockDuration, byte orderingChannel) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_Shutdown__SWIG_1(swigCPtr, blockDuration, orderingChannel);
  }

  public override void Shutdown(uint blockDuration) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_Shutdown__SWIG_2(swigCPtr, blockDuration);
  }

  public override bool IsActive() {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_IsActive(swigCPtr);
    return ret;
  }

  public override uint GetNextSendReceipt() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetNextSendReceipt(swigCPtr);
    return ret;
  }

  public override uint IncrementNextSendReceipt() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_IncrementNextSendReceipt(swigCPtr);
    return ret;
  }

  public override uint Send(string data, int length, PacketPriority priority, PacketReliability reliability, char orderingChannel, AddressOrGUID systemIdentifier, bool broadcast, uint forceReceiptNumber) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Send__SWIG_0(swigCPtr, data, length, (int)priority, (int)reliability, orderingChannel, AddressOrGUID.getCPtr(systemIdentifier), broadcast, forceReceiptNumber);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override uint Send(string data, int length, PacketPriority priority, PacketReliability reliability, char orderingChannel, AddressOrGUID systemIdentifier, bool broadcast) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Send__SWIG_1(swigCPtr, data, length, (int)priority, (int)reliability, orderingChannel, AddressOrGUID.getCPtr(systemIdentifier), broadcast);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void SendLoopback(string data, int length) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SendLoopback__SWIG_0(swigCPtr, data, length);
  }

  public override uint Send(BitStream bitStream, PacketPriority priority, PacketReliability reliability, char orderingChannel, AddressOrGUID systemIdentifier, bool broadcast, uint forceReceiptNumber) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Send__SWIG_2(swigCPtr, BitStream.getCPtr(bitStream), (int)priority, (int)reliability, orderingChannel, AddressOrGUID.getCPtr(systemIdentifier), broadcast, forceReceiptNumber);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override uint Send(BitStream bitStream, PacketPriority priority, PacketReliability reliability, char orderingChannel, AddressOrGUID systemIdentifier, bool broadcast) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Send__SWIG_3(swigCPtr, BitStream.getCPtr(bitStream), (int)priority, (int)reliability, orderingChannel, AddressOrGUID.getCPtr(systemIdentifier), broadcast);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override Packet Receive() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_Receive(swigCPtr);
    Packet ret = (cPtr == global::System.IntPtr.Zero) ? null : new Packet(cPtr, false);
    return ret;
  }

  public override void DeallocatePacket(Packet packet) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_DeallocatePacket(swigCPtr, Packet.getCPtr(packet));
  }

  public override uint GetMaximumNumberOfPeers() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetMaximumNumberOfPeers(swigCPtr);
    return ret;
  }

  public override void CloseConnection(AddressOrGUID target, bool sendDisconnectionNotification, byte orderingChannel, PacketPriority disconnectionNotificationPriority) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_CloseConnection__SWIG_0(swigCPtr, AddressOrGUID.getCPtr(target), sendDisconnectionNotification, orderingChannel, (int)disconnectionNotificationPriority);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void CloseConnection(AddressOrGUID target, bool sendDisconnectionNotification, byte orderingChannel) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_CloseConnection__SWIG_1(swigCPtr, AddressOrGUID.getCPtr(target), sendDisconnectionNotification, orderingChannel);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void CloseConnection(AddressOrGUID target, bool sendDisconnectionNotification) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_CloseConnection__SWIG_2(swigCPtr, AddressOrGUID.getCPtr(target), sendDisconnectionNotification);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void CancelConnectionAttempt(SystemAddress target) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_CancelConnectionAttempt(swigCPtr, SystemAddress.getCPtr(target));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ConnectionState GetConnectionState(AddressOrGUID systemIdentifier) {
    ConnectionState ret = (ConnectionState)RakNetPINVOKE.CSharp_RakNet_RakPeer_GetConnectionState(swigCPtr, AddressOrGUID.getCPtr(systemIdentifier));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int GetIndexFromSystemAddress(SystemAddress systemAddress) {
    int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetIndexFromSystemAddress(swigCPtr, SystemAddress.getCPtr(systemAddress));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SystemAddress GetSystemAddressFromIndex(uint index) {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetSystemAddressFromIndex(swigCPtr, index), true);
    return ret;
  }

  public override RakNetGUID GetGUIDFromIndex(uint index) {
    RakNetGUID ret = new RakNetGUID(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetGUIDFromIndex(swigCPtr, index), true);
    return ret;
  }

  public override void GetSystemList(RakNetListSystemAddress addresses, RakNetListRakNetGUID guids) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_GetSystemList(swigCPtr, RakNetListSystemAddress.getCPtr(addresses), RakNetListRakNetGUID.getCPtr(guids));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void AddToBanList(string IP, uint milliseconds) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_AddToBanList__SWIG_0(swigCPtr, IP, milliseconds);
  }

  public override void AddToBanList(string IP) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_AddToBanList__SWIG_1(swigCPtr, IP);
  }

  public override void RemoveFromBanList(string IP) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoveFromBanList(swigCPtr, IP);
  }

  public override void ClearBanList() {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_ClearBanList(swigCPtr);
  }

  public override bool IsBanned(string IP) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_IsBanned(swigCPtr, IP);
    return ret;
  }

  public override void SetLimitIPConnectionFrequency(bool b) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetLimitIPConnectionFrequency(swigCPtr, b);
  }

  public override void Ping(SystemAddress target) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_Ping__SWIG_0(swigCPtr, SystemAddress.getCPtr(target));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool Ping(string host, ushort remotePort, bool onlyReplyOnAcceptingConnections, uint connectionSocketIndex) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Ping__SWIG_1(swigCPtr, host, remotePort, onlyReplyOnAcceptingConnections, connectionSocketIndex);
    return ret;
  }

  public override bool Ping(string host, ushort remotePort, bool onlyReplyOnAcceptingConnections) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Ping__SWIG_2(swigCPtr, host, remotePort, onlyReplyOnAcceptingConnections);
    return ret;
  }

  public override int GetAveragePing(AddressOrGUID systemIdentifier) {
    int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetAveragePing(swigCPtr, AddressOrGUID.getCPtr(systemIdentifier));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int GetLastPing(AddressOrGUID systemIdentifier) {
    int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetLastPing(swigCPtr, AddressOrGUID.getCPtr(systemIdentifier));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int GetLowestPing(AddressOrGUID systemIdentifier) {
    int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetLowestPing(swigCPtr, AddressOrGUID.getCPtr(systemIdentifier));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void SetOccasionalPing(bool doPing) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetOccasionalPing(swigCPtr, doPing);
  }

  public override ulong GetClockDifferential(AddressOrGUID systemIdentifier) {
    ulong ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetClockDifferential(swigCPtr, AddressOrGUID.getCPtr(systemIdentifier));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void SetOfflinePingResponse(string data, uint length) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetOfflinePingResponse__SWIG_0(swigCPtr, data, length);
  }

  public override SystemAddress GetInternalID(SystemAddress systemAddress, int index) {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetInternalID__SWIG_0(swigCPtr, SystemAddress.getCPtr(systemAddress), index), true);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SystemAddress GetInternalID(SystemAddress systemAddress) {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetInternalID__SWIG_1(swigCPtr, SystemAddress.getCPtr(systemAddress)), true);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SystemAddress GetInternalID() {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetInternalID__SWIG_2(swigCPtr), true);
    return ret;
  }

  public override void SetInternalID(SystemAddress systemAddress, int index) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetInternalID__SWIG_0(swigCPtr, SystemAddress.getCPtr(systemAddress), index);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void SetInternalID(SystemAddress systemAddress) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetInternalID__SWIG_1(swigCPtr, SystemAddress.getCPtr(systemAddress));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override SystemAddress GetExternalID(SystemAddress target) {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetExternalID(swigCPtr, SystemAddress.getCPtr(target)), true);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override RakNetGUID GetMyGUID() {
    RakNetGUID ret = new RakNetGUID(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetMyGUID(swigCPtr), true);
    return ret;
  }

  public override SystemAddress GetMyBoundAddress(int socketIndex) {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetMyBoundAddress__SWIG_0(swigCPtr, socketIndex), true);
    return ret;
  }

  public override SystemAddress GetMyBoundAddress() {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetMyBoundAddress__SWIG_1(swigCPtr), true);
    return ret;
  }

  public override RakNetGUID GetGuidFromSystemAddress(SystemAddress input) {
    RakNetGUID ret = new RakNetGUID(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetGuidFromSystemAddress(swigCPtr, SystemAddress.getCPtr(input)), false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SystemAddress GetSystemAddressFromGuid(RakNetGUID input) {
    SystemAddress ret = new SystemAddress(RakNetPINVOKE.CSharp_RakNet_RakPeer_GetSystemAddressFromGuid(swigCPtr, RakNetGUID.getCPtr(input)), true);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool GetClientPublicKeyFromSystemAddress(SystemAddress input, string client_public_key) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetClientPublicKeyFromSystemAddress(swigCPtr, SystemAddress.getCPtr(input), client_public_key);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void SetTimeoutTime(uint timeMS, SystemAddress target) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetTimeoutTime(swigCPtr, timeMS, SystemAddress.getCPtr(target));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override uint GetTimeoutTime(SystemAddress target) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetTimeoutTime(swigCPtr, SystemAddress.getCPtr(target));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int GetMTUSize(SystemAddress target) {
    int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetMTUSize(swigCPtr, SystemAddress.getCPtr(target));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override uint GetNumberOfAddresses() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetNumberOfAddresses(swigCPtr);
    return ret;
  }

  public override string GetLocalIP(uint index) {
    string ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetLocalIP(swigCPtr, index);
    return ret;
  }

  public override bool IsLocalIP(string ip) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_IsLocalIP(swigCPtr, ip);
    return ret;
  }

  public override void AllowConnectionResponseIPMigration(bool allow) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_AllowConnectionResponseIPMigration(swigCPtr, allow);
  }

  public override bool AdvertiseSystem(string host, ushort remotePort, string data, int dataLength, uint connectionSocketIndex) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_AdvertiseSystem__SWIG_0(swigCPtr, host, remotePort, data, dataLength, connectionSocketIndex);
    return ret;
  }

  public override bool AdvertiseSystem(string host, ushort remotePort, string data, int dataLength) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_AdvertiseSystem__SWIG_1(swigCPtr, host, remotePort, data, dataLength);
    return ret;
  }

  public override void SetSplitMessageProgressInterval(int interval) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetSplitMessageProgressInterval(swigCPtr, interval);
  }

  public override int GetSplitMessageProgressInterval() {
    int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetSplitMessageProgressInterval(swigCPtr);
    return ret;
  }

  public override void SetUnreliableTimeout(uint timeoutMS) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetUnreliableTimeout(swigCPtr, timeoutMS);
  }

  public override void SendTTL(string host, ushort remotePort, int ttl, uint connectionSocketIndex) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SendTTL__SWIG_0(swigCPtr, host, remotePort, ttl, connectionSocketIndex);
  }

  public override void SendTTL(string host, ushort remotePort, int ttl) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SendTTL__SWIG_1(swigCPtr, host, remotePort, ttl);
  }

  public override void AttachPlugin(PluginInterface2 plugin) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_AttachPlugin(swigCPtr, PluginInterface2.getCPtr(plugin));
  }

  public override void DetachPlugin(PluginInterface2 messageHandler) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_DetachPlugin(swigCPtr, PluginInterface2.getCPtr(messageHandler));
  }

  public override void PushBackPacket(Packet packet, bool pushAtHead) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_PushBackPacket(swigCPtr, Packet.getCPtr(packet), pushAtHead);
  }

  public override void ChangeSystemAddress(RakNetGUID guid, SystemAddress systemAddress) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_ChangeSystemAddress(swigCPtr, RakNetGUID.getCPtr(guid), SystemAddress.getCPtr(systemAddress));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override Packet AllocatePacket(uint dataSize) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_AllocatePacket(swigCPtr, dataSize);
    Packet ret = (cPtr == global::System.IntPtr.Zero) ? null : new Packet(cPtr, false);
    return ret;
  }

  public override void GetSockets(SWIGTYPE_p_DataStructures__ListT_RakNetSocket2_p_t sockets) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_GetSockets(swigCPtr, SWIGTYPE_p_DataStructures__ListT_RakNetSocket2_p_t.getCPtr(sockets));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void WriteOutOfBandHeader(BitStream bitStream) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_WriteOutOfBandHeader(swigCPtr, BitStream.getCPtr(bitStream));
  }

  public override void ApplyNetworkSimulator(float packetloss, ushort minExtraPing, ushort extraPingVariance) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_ApplyNetworkSimulator(swigCPtr, packetloss, minExtraPing, extraPingVariance);
  }

  public override void SetPerConnectionOutgoingBandwidthLimit(uint maxBitsPerSecond) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetPerConnectionOutgoingBandwidthLimit(swigCPtr, maxBitsPerSecond);
  }

  public override bool IsNetworkSimulatorActive() {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_IsNetworkSimulatorActive(swigCPtr);
    return ret;
  }

  public override RakNetStatistics GetStatistics(SystemAddress systemAddress, RakNetStatistics rns) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetStatistics__SWIG_0(swigCPtr, SystemAddress.getCPtr(systemAddress), RakNetStatistics.getCPtr(rns));
    RakNetStatistics ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakNetStatistics(cPtr, false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override RakNetStatistics GetStatistics(SystemAddress systemAddress) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetStatistics__SWIG_1(swigCPtr, SystemAddress.getCPtr(systemAddress));
    RakNetStatistics ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakNetStatistics(cPtr, false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool GetStatistics(uint index, RakNetStatistics rns) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetStatistics__SWIG_2(swigCPtr, index, RakNetStatistics.getCPtr(rns));
    return ret;
  }

  public override uint GetReceiveBufferSize() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetReceiveBufferSize(swigCPtr);
    return ret;
  }

  public override bool RunUpdateCycle(BitStream updateBitStream) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RunUpdateCycle(swigCPtr, BitStream.getCPtr(updateBitStream));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool SendOutOfBand(string host, ushort remotePort, string data, uint dataLength, uint connectionSocketIndex) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_SendOutOfBand__SWIG_0(swigCPtr, host, remotePort, data, dataLength, connectionSocketIndex);
    return ret;
  }

  public override bool SendOutOfBand(string host, ushort remotePort, string data, uint dataLength) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_SendOutOfBand__SWIG_1(swigCPtr, host, remotePort, data, dataLength);
    return ret;
  }

  public class PingAndClockDifferential : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal PingAndClockDifferential(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PingAndClockDifferential obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~PingAndClockDifferential() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            RakNetPINVOKE.CSharp_RakNet_delete_RakPeer_PingAndClockDifferential(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public ushort pingTime {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_PingAndClockDifferential_pingTime_set(swigCPtr, value);
      } 
      get {
        ushort ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_PingAndClockDifferential_pingTime_get(swigCPtr);
        return ret;
      } 
    }
  
    public ulong clockDifferential {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_PingAndClockDifferential_clockDifferential_set(swigCPtr, value);
      } 
      get {
        ulong ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_PingAndClockDifferential_clockDifferential_get(swigCPtr);
        return ret;
      } 
    }
  
    public PingAndClockDifferential() : this(RakNetPINVOKE.CSharp_RakNet_new_RakPeer_PingAndClockDifferential(), true) {
    }
  
  }

  public class RemoteSystemStruct : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal RemoteSystemStruct(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RemoteSystemStruct obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~RemoteSystemStruct() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            RakNetPINVOKE.CSharp_RakNet_delete_RakPeer_RemoteSystemStruct(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public bool isActive {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_isActive_set(swigCPtr, value);
      } 
      get {
        bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_isActive_get(swigCPtr);
        return ret;
      } 
    }
  
    public SystemAddress systemAddress {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_systemAddress_set(swigCPtr, SystemAddress.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_systemAddress_get(swigCPtr);
        SystemAddress ret = (cPtr == global::System.IntPtr.Zero) ? null : new SystemAddress(cPtr, false);
        return ret;
      } 
    }
  
    public SystemAddress myExternalSystemAddress {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_myExternalSystemAddress_set(swigCPtr, SystemAddress.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_myExternalSystemAddress_get(swigCPtr);
        SystemAddress ret = (cPtr == global::System.IntPtr.Zero) ? null : new SystemAddress(cPtr, false);
        return ret;
      } 
    }
  
    public SystemAddress theirInternalSystemAddress {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_theirInternalSystemAddress_set(swigCPtr, SystemAddress.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_theirInternalSystemAddress_get(swigCPtr);
        SystemAddress ret = (cPtr == global::System.IntPtr.Zero) ? null : new SystemAddress(cPtr, false);
        return ret;
      } 
    }
  
    public SWIGTYPE_p_ReliabilityLayer reliabilityLayer {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_reliabilityLayer_set(swigCPtr, SWIGTYPE_p_ReliabilityLayer.getCPtr(value));
        if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        SWIGTYPE_p_ReliabilityLayer ret = new SWIGTYPE_p_ReliabilityLayer(RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_reliabilityLayer_get(swigCPtr), true);
        if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public bool weInitiatedTheConnection {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_weInitiatedTheConnection_set(swigCPtr, value);
      } 
      get {
        bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_weInitiatedTheConnection_get(swigCPtr);
        return ret;
      } 
    }
  
    public RakPeer.PingAndClockDifferential pingAndClockDifferential {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_pingAndClockDifferential_set(swigCPtr, RakPeer.PingAndClockDifferential.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_pingAndClockDifferential_get(swigCPtr);
        RakPeer.PingAndClockDifferential ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakPeer.PingAndClockDifferential(cPtr, false);
        return ret;
      } 
    }
  
    public ulong pingAndClockDifferentialWriteIndex {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_pingAndClockDifferentialWriteIndex_set(swigCPtr, value);
      } 
      get {
        ulong ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_pingAndClockDifferentialWriteIndex_get(swigCPtr);
        return ret;
      } 
    }
  
    public ushort lowestPing {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_lowestPing_set(swigCPtr, value);
      } 
      get {
        ushort ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_lowestPing_get(swigCPtr);
        return ret;
      } 
    }
  
    public ulong nextPingTime {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_nextPingTime_set(swigCPtr, value);
      } 
      get {
        ulong ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_nextPingTime_get(swigCPtr);
        return ret;
      } 
    }
  
    public ulong lastReliableSend {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_lastReliableSend_set(swigCPtr, value);
      } 
      get {
        ulong ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_lastReliableSend_get(swigCPtr);
        return ret;
      } 
    }
  
    public ulong connectionTime {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_connectionTime_set(swigCPtr, value);
      } 
      get {
        ulong ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_connectionTime_get(swigCPtr);
        return ret;
      } 
    }
  
    public RakNetGUID guid {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_guid_set(swigCPtr, RakNetGUID.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_guid_get(swigCPtr);
        RakNetGUID ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakNetGUID(cPtr, false);
        return ret;
      } 
    }
  
    public int MTUSize {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_MTUSize_set(swigCPtr, value);
      } 
      get {
        int ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_MTUSize_get(swigCPtr);
        return ret;
      } 
    }
  
    public SWIGTYPE_p_RakNetSocket2 rakNetSocket {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_rakNetSocket_set(swigCPtr, SWIGTYPE_p_RakNetSocket2.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_rakNetSocket_get(swigCPtr);
        SWIGTYPE_p_RakNetSocket2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_RakNetSocket2(cPtr, false);
        return ret;
      } 
    }
  
    public ushort remoteSystemIndex {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_remoteSystemIndex_set(swigCPtr, value);
      } 
      get {
        ushort ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_remoteSystemIndex_get(swigCPtr);
        return ret;
      } 
    }
  
    public RakPeer.RemoteSystemStruct.ConnectMode connectMode {
      set {
        RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_connectMode_set(swigCPtr, (int)value);
      } 
      get {
        RakPeer.RemoteSystemStruct.ConnectMode ret = (RakPeer.RemoteSystemStruct.ConnectMode)RakNetPINVOKE.CSharp_RakNet_RakPeer_RemoteSystemStruct_connectMode_get(swigCPtr);
        return ret;
      } 
    }
  
    public RemoteSystemStruct() : this(RakNetPINVOKE.CSharp_RakNet_new_RakPeer_RemoteSystemStruct(), true) {
    }
  
    public enum ConnectMode {
      NO_ACTION,
      DISCONNECT_ASAP,
      DISCONNECT_ASAP_SILENTLY,
      DISCONNECT_ON_NO_ACK,
      REQUESTED_CONNECTION,
      HANDLING_CONNECTION_REQUEST,
      UNVERIFIED_SENDER,
      CONNECTED
    }
  
  }

  public new uint Send(byte[] inByteArray, int length, PacketPriority priority, PacketReliability reliability, char orderingChannel, AddressOrGUID systemIdentifier, bool broadcast) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_Send__SWIG_4(swigCPtr, inByteArray, length, (int)priority, (int)reliability, orderingChannel, AddressOrGUID.getCPtr(systemIdentifier), broadcast);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new void SendLoopback(byte[] inByteArray, int length) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SendLoopback__SWIG_1(swigCPtr, inByteArray, length);
  }

  public new void SetOfflinePingResponse(byte[] inByteArray, uint length) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetOfflinePingResponse__SWIG_1(swigCPtr, inByteArray, length);
  }

  public new bool AdvertiseSystem(string host, ushort remotePort, byte[] inByteArray, int dataLength, uint connectionSocketIndex) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_AdvertiseSystem__SWIG_2(swigCPtr, host, remotePort, inByteArray, dataLength, connectionSocketIndex);
    return ret;
  }

  public new bool AdvertiseSystem(string host, ushort remotePort, byte[] inByteArray, int dataLength) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_AdvertiseSystem__SWIG_3(swigCPtr, host, remotePort, inByteArray, dataLength);
    return ret;
  }

  private string CSharpGetIncomingPasswordHelper(string passwordData, ref int passwordDataLength) {
    string ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_CSharpGetIncomingPasswordHelper(swigCPtr, passwordData, ref passwordDataLength);
    return ret;
  }

  public new void SetIncomingPassword(byte[] passwordDataByteArray, int passwordDataLength) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_SetIncomingPassword__SWIG_1(swigCPtr, passwordDataByteArray, passwordDataLength);
  }

  public new void GetIncomingPassword(byte[] passwordDataByteArray, ref int passwordDataLength) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_GetIncomingPassword(swigCPtr, passwordDataByteArray, ref passwordDataLength);
  }

  private void CSharpGetOfflinePingResponseHelper(byte[] inOutByteArray, out uint outLength) {
    RakNetPINVOKE.CSharp_RakNet_RakPeer_CSharpGetOfflinePingResponseHelper(swigCPtr, inOutByteArray, out outLength);
  }

  public new bool GetConnectionList(RakNetListSystemAddress remoteSystems, ref ushort numberOfSystems) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_RakPeer_GetConnectionList(swigCPtr, RakNetListSystemAddress.getCPtr(remoteSystems), ref numberOfSystems);
    return ret;
  }

}

}
