//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class Row : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Row(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Row obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Row() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_Row(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public RakNetListCellPointer cells {
    set {
      RakNetPINVOKE.CSharp_RakNet_Row_cells_set(swigCPtr, RakNetListCellPointer.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_Row_cells_get(swigCPtr);
      RakNetListCellPointer ret = (cPtr == global::System.IntPtr.Zero) ? null : new RakNetListCellPointer(cPtr, false);
      return ret;
    } 
  }

  public void UpdateCell(uint columnIndex, double value) {
    RakNetPINVOKE.CSharp_RakNet_Row_UpdateCell__SWIG_0(swigCPtr, columnIndex, value);
  }

  public void UpdateCell(uint columnIndex, string str) {
    RakNetPINVOKE.CSharp_RakNet_Row_UpdateCell__SWIG_1(swigCPtr, columnIndex, str);
  }

  public void UpdateCell(uint columnIndex, int byteLength, byte[] inByteArray) {
    RakNetPINVOKE.CSharp_RakNet_Row_UpdateCell__SWIG_2(swigCPtr, columnIndex, byteLength, inByteArray);
  }

  public Row() : this(RakNetPINVOKE.CSharp_RakNet_new_Row(), true) {
  }

}

}
