//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class TeamSelection : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TeamSelection(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TeamSelection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TeamSelection() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_TeamSelection(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public TeamSelection() : this(RakNetPINVOKE.CSharp_RakNet_new_TeamSelection__SWIG_0(), true) {
  }

  public TeamSelection(JoinTeamType itt) : this(RakNetPINVOKE.CSharp_RakNet_new_TeamSelection__SWIG_1((int)itt), true) {
  }

  public TeamSelection(JoinTeamType itt, TM_Team param) : this(RakNetPINVOKE.CSharp_RakNet_new_TeamSelection__SWIG_2((int)itt, TM_Team.getCPtr(param)), true) {
  }

  public TeamSelection(JoinTeamType itt, byte param) : this(RakNetPINVOKE.CSharp_RakNet_new_TeamSelection__SWIG_3((int)itt, param), true) {
  }

  public JoinTeamType joinTeamType {
    set {
      RakNetPINVOKE.CSharp_RakNet_TeamSelection_joinTeamType_set(swigCPtr, (int)value);
    } 
    get {
      JoinTeamType ret = (JoinTeamType)RakNetPINVOKE.CSharp_RakNet_TeamSelection_joinTeamType_get(swigCPtr);
      return ret;
    } 
  }

  public static TeamSelection AnyAvailable() {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_RakNet_TeamSelection_AnyAvailable(), true);
    return ret;
  }

  public static TeamSelection SpecificTeam(TM_Team specificTeamToJoin) {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_RakNet_TeamSelection_SpecificTeam(TM_Team.getCPtr(specificTeamToJoin)), true);
    return ret;
  }

  public static TeamSelection NoTeam(byte noTeamSubcategory) {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_RakNet_TeamSelection_NoTeam(noTeamSubcategory), true);
    return ret;
  }

}

}
