//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace RakNet {

public class TM_TeamMember : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TM_TeamMember(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TM_TeamMember obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TM_TeamMember() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.CSharp_RakNet_delete_TM_TeamMember(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static TM_TeamMember GetInstance() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetInstance();
    TM_TeamMember ret = (cPtr == global::System.IntPtr.Zero) ? null : new TM_TeamMember(cPtr, false);
    return ret;
  }

  public static void DestroyInstance(TM_TeamMember i) {
    RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_DestroyInstance(TM_TeamMember.getCPtr(i));
  }

  public TM_TeamMember() : this(RakNetPINVOKE.CSharp_RakNet_new_TM_TeamMember(), true) {
  }

  public bool RequestTeam(TeamSelection teamSelection) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestTeam(swigCPtr, TeamSelection.getCPtr(teamSelection));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool RequestTeamSwitch(TM_Team teamToJoin, TM_Team teamToLeave) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestTeamSwitch(swigCPtr, TM_Team.getCPtr(teamToJoin), TM_Team.getCPtr(teamToLeave));
    return ret;
  }

  public TeamSelection GetRequestedTeam() {
    TeamSelection ret = new TeamSelection(RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetRequestedTeam(swigCPtr), true);
    return ret;
  }

  public void GetRequestedSpecificTeams(SWIGTYPE_p_DataStructures__ListT_RakNet__TM_Team_p_t requestedTeams) {
    RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetRequestedSpecificTeams(swigCPtr, SWIGTYPE_p_DataStructures__ListT_RakNet__TM_Team_p_t.getCPtr(requestedTeams));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasRequestedTeam(TM_Team team) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_HasRequestedTeam(swigCPtr, TM_Team.getCPtr(team));
    return ret;
  }

  public uint GetRequestedTeamIndex(TM_Team team) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetRequestedTeamIndex(swigCPtr, TM_Team.getCPtr(team));
    return ret;
  }

  public uint GetRequestedTeamCount() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetRequestedTeamCount(swigCPtr);
    return ret;
  }

  public bool CancelTeamRequest(TM_Team specificTeamToCancel) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_CancelTeamRequest(swigCPtr, TM_Team.getCPtr(specificTeamToCancel));
    return ret;
  }

  public bool LeaveTeam(TM_Team team, byte _noTeamSubcategory) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_LeaveTeam(swigCPtr, TM_Team.getCPtr(team), _noTeamSubcategory);
    return ret;
  }

  public bool LeaveAllTeams(byte noTeamSubcategory) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_LeaveAllTeams(swigCPtr, noTeamSubcategory);
    return ret;
  }

  public TM_Team GetCurrentTeam() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetCurrentTeam(swigCPtr);
    TM_Team ret = (cPtr == global::System.IntPtr.Zero) ? null : new TM_Team(cPtr, false);
    return ret;
  }

  public uint GetCurrentTeamCount() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetCurrentTeamCount(swigCPtr);
    return ret;
  }

  public TM_Team GetCurrentTeamByIndex(uint index) {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetCurrentTeamByIndex(swigCPtr, index);
    TM_Team ret = (cPtr == global::System.IntPtr.Zero) ? null : new TM_Team(cPtr, false);
    return ret;
  }

  public void GetCurrentTeams(SWIGTYPE_p_DataStructures__ListT_RakNet__TM_Team_p_t _teams) {
    RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetCurrentTeams(swigCPtr, SWIGTYPE_p_DataStructures__ListT_RakNet__TM_Team_p_t.getCPtr(_teams));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetLastTeams(SWIGTYPE_p_DataStructures__ListT_RakNet__TM_Team_p_t _teams) {
    RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetLastTeams(swigCPtr, SWIGTYPE_p_DataStructures__ListT_RakNet__TM_Team_p_t.getCPtr(_teams));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsOnTeam(TM_Team team) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_IsOnTeam(swigCPtr, TM_Team.getCPtr(team));
    return ret;
  }

  public ulong GetNetworkID() {
    ulong ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetNetworkID(swigCPtr);
    return ret;
  }

  public TM_World GetTM_World() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetTM_World(swigCPtr);
    TM_World ret = (cPtr == global::System.IntPtr.Zero) ? null : new TM_World(cPtr, false);
    return ret;
  }

  public void SerializeConstruction(BitStream constructionBitstream) {
    RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_SerializeConstruction(swigCPtr, BitStream.getCPtr(constructionBitstream));
  }

  public bool DeserializeConstruction(TeamManager teamManager, BitStream constructionBitstream) {
    bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_DeserializeConstruction(swigCPtr, TeamManager.getCPtr(teamManager), BitStream.getCPtr(constructionBitstream));
    return ret;
  }

  public void SetOwner(SWIGTYPE_p_void o) {
    RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_SetOwner(swigCPtr, SWIGTYPE_p_void.getCPtr(o));
  }

  public SWIGTYPE_p_void GetOwner() {
    global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetOwner(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public byte GetNoTeamId() {
    byte ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetNoTeamId(swigCPtr);
    return ret;
  }

  public uint GetWorldIndex() {
    uint ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_GetWorldIndex(swigCPtr);
    return ret;
  }

  public static uint ToUint32(ulong g) {
    uint ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_ToUint32(g);
    return ret;
  }

  public class RequestedTeam : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal RequestedTeam(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RequestedTeam obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~RequestedTeam() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            RakNetPINVOKE.CSharp_RakNet_delete_TM_TeamMember_RequestedTeam(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public ulong whenRequested {
      set {
        RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_whenRequested_set(swigCPtr, value);
      } 
      get {
        ulong ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_whenRequested_get(swigCPtr);
        return ret;
      } 
    }
  
    public uint requestIndex {
      set {
        RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_requestIndex_set(swigCPtr, value);
      } 
      get {
        uint ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_requestIndex_get(swigCPtr);
        return ret;
      } 
    }
  
    public TM_Team requested {
      set {
        RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_requested_set(swigCPtr, TM_Team.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_requested_get(swigCPtr);
        TM_Team ret = (cPtr == global::System.IntPtr.Zero) ? null : new TM_Team(cPtr, false);
        return ret;
      } 
    }
  
    public bool isTeamSwitch {
      set {
        RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_isTeamSwitch_set(swigCPtr, value);
      } 
      get {
        bool ret = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_isTeamSwitch_get(swigCPtr);
        return ret;
      } 
    }
  
    public TM_Team teamToLeave {
      set {
        RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_teamToLeave_set(swigCPtr, TM_Team.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = RakNetPINVOKE.CSharp_RakNet_TM_TeamMember_RequestedTeam_teamToLeave_get(swigCPtr);
        TM_Team ret = (cPtr == global::System.IntPtr.Zero) ? null : new TM_Team(cPtr, false);
        return ret;
      } 
    }
  
    public RequestedTeam() : this(RakNetPINVOKE.CSharp_RakNet_new_TM_TeamMember_RequestedTeam(), true) {
    }
  
  }

}

}
